Repository gardener/egress-filter-refresher, pull requests merged in 2024-10, with the labels that each got.

#48 fix: prepareAddrs trims /128 suffixes for ipv6 filters
  cmd/main.go
  pkg/netconfig/netconfig.go
  pkg/netconfig/netconfig_test.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/s

#50 Introduce `gosec` for Static Application Security Testing (SAST)
  .gitignore
  Makefile
  hack/sast.sh
  hack/tools/install-gosec.sh
  hack/tools/tools.mk
  pkg/netconfig/netutils.go
Labels: area/networking, area/security, kind/enhancement, needs/ok-to-test, needs/review, size/m, area/compliance

#49 Cleanup old egress rules after applying a new blocking mode
  Dockerfile
  Makefile
  cmd/main.go
  pkg/netconfig/netconfig.go
  pkg/netconfig/netconfig_test.go
  pkg/netconfig/netutils.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/l

#51 Add SAST logs to OCM component descriptor
  .ci/pipeline_definitions
Labels: needs/ok-to-test, needs/review, size/xs

#52 bump golangci-lint
  hack/tools/tools.mk
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs
